version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.3-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    networks:
          - myhealth-network
  pgadmin:
      image: dpage/pgadmin4
      restart: always
      ports:
        - "5050:80" 
      environment:
        - PGADMIN_DEFAULT_EMAIL=myhealth@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=myhealth123
      depends_on:
        - postgres
      networks:
        - myhealth-network
      
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=myhealth_db
    networks:
      myhealth-network:
            ipv4_address: 170.11.0.3


networks:
  myhealth-network:
    driver: bridge
    ipam:
     config:
       - subnet: 170.11.0.0/16
         gateway: 170.11.0.1